apiVersion: enforcement.globo.com/v1beta1
kind: ClusterRule
metadata:
  name: dev-rule #Rule name
spec:
  enforcements: #List of packages that will be installed in the filtered clusters
    - name: guestbook #Name
      repo: https://github.com/argoproj/argocd-example-apps #Git repository
      path: guestbook #Package folder within the repository
  source:
    rancher: #Enforcement will filter all clusters that match the rules defined in filters, labels and ignore. All of these fields are optional.
      labels: #Labels registered to the cluster
        cattle.io/creator: "norman"
      ignore: #Ignore clusters that have the names listed below.
        - local
        - acs-lb-chart
        - argocd-dev
        - csccm-fe






